const data = [
  {
    id: 1,
    beds: 2,
    baths: 4,
    title: "Ikoyi House",
    price: 250,
    img: "Hackmamba/Images/pet1.jpg",
    video: "/Hackmamba/Videos/pet1",
  },
  {
    id: 2,
    beds: 2,
    baths: 4,
    title: "Ikoyi House",
    price: 250,
    img: "Hackmamba/Images/pet2.jpg",
    video: "/Hackmamba/Videos/pet2",
  },
  {
    id: 3,
    beds: 2,
    baths: 4,
    title: "Ikoyi House",
    price: 250,
    img: "Hackmamba/Images/pet3.jpg",
    video: "/Hackmamba/Videos/pet3",
  },
  {
    id: 4,
    beds: 2,
    baths: 4,
    title: "Ikoyi House",
    price: 250,
    img: "Hackmamba/Images/pet4.jpg",
    video: "/Hackmamba/Videos/pet4",
  },
  {
    id: 5,
    beds: 2,
    baths: 4,
    title: "Ikoyi House",
    price: 250,
    img: "Hackmamba/Images/pet5.jpg",
    video: "/Hackmamba/Videos/pet5",
  },
  {
    id: 6,
    beds: 2,
    baths: 4,
    title: "Ikoyi House",
    price: 250,
    img: "Hackmamba/Images/pet6.jpg",
    video: "/Hackmamba/Videos/pet6",
  },
  {
    id: 7,
    beds: 2,
    baths: 4,
    title: "Ikoyi House",
    price: 250,
    img: "Hackmamba/Images/pet7.jpg",
    video: "/Hackmamba/Videos/pet7",
  },
  {
    id: 8,
    beds: 2,
    baths: 4,
    title: "Ikoyi House",
    price: 250,
    img: "Hackmamba/Images/pet8.jpg",
    video: "/Hackmamba/Videos/pet8",
  },
  {
    id: 9,
    beds: 2,
    baths: 4,
    title: "Ikoyi House",
    price: 250,
    img: "Hackmamba/Images/pet9.jpg",
    video: "/Hackmamba/Videos/pet9",
  },
  {
    id: 10,
    beds: 2,
    baths: 4,
    title: "Ikoyi House",
    price: 250,
    img: "Hackmamba/Images/pet10.jpg",
    video: "/Hackmamba/Videos/pet10",
  },
];

export default data;
