const data = [
  {
    id: 1,
    beds: 2,
    baths: 4,
    title: "First Pet",
    price: 250,
    img: "https://res.cloudinary.com/nefejames/image/upload/q_auto,f_auto,w_auto/Hackmamba/Images/pet1.jpg",
    video: "/Hackmamba/Videos/pet1",
  },
  {
    id: 2,
    beds: 2,
    baths: 4,
    title: "Second Pet",
    price: 250,
    img: "https://res.cloudinary.com/nefejames/image/upload/q_auto,f_auto,w_auto/Hackmamba/Images/pet2.jpg",
    video: "/Hackmamba/Videos/pet2",
  },
  {
    id: 3,
    beds: 2,
    baths: 4,
    title: "Third Pet",
    price: 250,
    img: "https://res.cloudinary.com/nefejames/image/upload/q_auto,f_auto,w_auto/Hackmamba/Images/pet3.jpg",
    video: "/Hackmamba/Videos/pet3",
  },
  {
    id: 4,
    beds: 2,
    baths: 4,
    title: "Fourth Pet",
    price: 250,
    img: "https://res.cloudinary.com/nefejames/image/upload/q_auto,f_auto,w_auto/Hackmamba/Images/pet4.jpg",
    video: "/Hackmamba/Videos/pet4",
  },
  {
    id: 5,
    beds: 2,
    baths: 4,
    title: "Fifth Pet",
    price: 250,
    img: "https://res.cloudinary.com/nefejames/image/upload/q_auto,f_auto,w_auto/Hackmamba/Images/pet5.jpg",
    video: "/Hackmamba/Videos/pet5",
  },
  {
    id: 6,
    beds: 2,
    baths: 4,
    title: "Sixth Pet",
    price: 250,
    img: "https://res.cloudinary.com/nefejames/image/upload/q_auto,f_auto,w_auto/Hackmamba/Images/pet6.jpg",
    video: "/Hackmamba/Videos/pet6",
  },
  {
    id: 7,
    beds: 2,
    baths: 4,
    title: "Seventh Pet",
    price: 250,
    img: "https://res.cloudinary.com/nefejames/image/upload/q_auto,f_auto,w_auto/Hackmamba/Images/pet7.jpg",
    video: "/Hackmamba/Videos/pet7",
  },
  {
    id: 8,
    beds: 2,
    baths: 4,
    title: "Eight Pet",
    price: 250,
    img: "https://res.cloudinary.com/nefejames/image/upload/q_auto,f_auto,w_auto/Hackmamba/Images/pet8.jpg",
    video: "/Hackmamba/Videos/pet8",
  },
  {
    id: 9,
    beds: 2,
    baths: 4,
    title: "Ninth Pet",
    price: 250,
    img: "https://res.cloudinary.com/nefejames/image/upload/q_auto,f_auto,w_auto/Hackmamba/Images/pet9.jpg",
    video: "/Hackmamba/Videos/pet9",
  },
  {
    id: 10,
    beds: 2,
    baths: 4,
    title: "Tenth Pet",
    price: 250,
    img: "https://res.cloudinary.com/nefejames/image/upload/q_auto,f_auto,w_auto/Hackmamba/Images/pet10.jpg",
    video: "/Hackmamba/Videos/pet10",
  },
];

export default data;
